export const IPC_CHANNELS = {
  browserSnapshot: "browser:snapshot",
  tabAction: "tab:action",
  tabReorder: "tab:reorder",
  navigate: "tab:navigate",
  sidebarOpen: "sidebar:open",
  sidebarResize: "sidebar:resize",
  uiSetUtilityDock: "ui:set-utility-dock",
  windowControl: "window:control",
  settingsGet: "settings:get",
  settingsPatch: "settings:patch",
  shieldSetGlobal: "shields:set-global",
  shieldSetSite: "shields:set-site",
  bookmarksToggle: "bookmarks:toggle",
  historyClear: "history:clear",
  historyDelete: "history:delete",
  downloadsAction: "downloads:action",
  modsImport: "mods:import",
  modsExport: "mods:export",
  modsToggle: "mods:toggle",
  aiRun: "ai:run",
  pipRequest: "tools:pip",
  screenshot: "tools:screenshot",
  cleaner: "tools:cleaner"
} as const;
